DROP TABLE IF EXISTS FACT_RESERVAS;
DROP TABLE IF EXISTS ODONTOLOGOS;
DROP TABLE IF EXISTS PACIENTES;

CREATE TABLE ODONTOLOGOS(
ID_ODONTOLOGO INT AUTO_INCREMENT  PRIMARY KEY, 
NOMBRE VARCHAR(55) NOT NULL, 
APELLIDO VARCHAR(55) NOT NULL, 
MATRICULA VARCHAR(50) NOT NULL); 

CREATE TABLE PACIENTES(
ID_PACIENTE INT AUTO_INCREMENT  PRIMARY KEY, 
NOMBRE VARCHAR(55) NOT NULL, 
APELLIDO VARCHAR(55) NOT NULL, 
DOMICILIO VARCHAR(50) NOT NULL, 
DNI INT, 
FECHALATA  DATE  );

CREATE TABLE FACT_RESERVAS(
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ODONTOLOGO INT,
FOREIGN KEY(ID_ODONTOLOGO) REFERENCES ODONTOLOGOS(ID_ODONTOLOGO ),
ID_PACIENTE INT,
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE ),
FECHACITA DATE);
